### ISSUE TITLE
The image from topic "/camera/image_raw" is caton

### ISSUE THREAD

**Issue by ccs-ros** [patrickelectric/bluerov_ros_playground#37]
Hi,when i run the ros_node to view image,i found the image from topic "/camera/image_raw" is caton.And there is high picture delay when the bluerov move.So that i can't use the image to run the orbslam2.Could you please give me some advice?Thank you!

**Comment by patrickelectric** [comment]
1- What is **caton** ?
2- The image is decoded from mp4 to a frame structure. You can probably change the code under [video.py](https://github.com/patrickelectric/bluerov_ros_playground/blob/master/src/bluerov/video.py), use the raw data if possible with a second udp port, or doing a faster decoder if possible, maybe in c++. You can check my [c++ example here](https://gist.github.com/patrickelectric/5dca1cb7cef4ffa7fbb6fb70dd9f9edc).
